### ISSUE TITLE
 graphs of longer stories are unreadable 

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#45] opened 2024-03-26 14:43 UTC
##### Story Navigator version
0.0.18

##### Orange version
3.36.2
Orange-text version: 1.15.0 
Orange-network version: 1.9.0 

##### Expected behavior
You can zoom in on the graph, so that is actually ok, but you (or at least I) cannot move the graph, so you can only zoom in on one aspect of the graph. Is it possible to display not ALL the subjects in the graph, but per segment only the 10 most mentioned subjects? 

##### Actual behavior
When I want to display the graph of the subjects of a longer story, the graph is unreadable. 

##### Steps to reproduce the behavior
1. create a graph of the subjects of e.g. the ‘over leven’ story or e.g. the Moataz Rageb story. 

##### Additional info (worksheets, data, screenshots, ...)
<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/a760593d-9f0a-4d3e-a547-1c671ae12dcd">

**Comment by kodymoodley** [comment] 2024-03-27 06:43
Not a bug. You can filter or reduce your results before displaying / visualising to make it easier to read.

**Comment by kodymoodley** [comment] 2024-03-28 09:04
Need to show an example workflow how to filter top N results for visualisation to avoid unreadability of plots. Must save this workflow also for workshop.

**Comment by kodymoodley** [comment] 2024-04-04 11:43
Fixed in #55

**Closed by kodymoodley** 2024-04-04 11:43 UTC
Labels: enhancement, workshop-april
